[phases.setup]
pkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run railway:build"]

[phases.start]
cmds = ["npm run railway:start"]

[static]
path = "dist/client"
spa = true