[phases.setup]
pkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:server", "npm run build:client"]

[phases.start]
cmds = ["npm run railway:start"]

[static]
path = "dist/client"
spa = true